name: build library

on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_call:

jobs:
  build-library:
    runs-on: ubuntu-latest
    container:
      image: rust:1.91-slim-trixie
    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y libclang-dev clang cmake wget ninja-build nodejs npm
          wget -qO /opt/wasi-sdk-24.0.tar.gz https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-24/wasi-sdk-24.0-x86_64-linux.tar.gz
          mkdir -p /opt/wasi-sdk-24.0
          tar -xf /opt/wasi-sdk-24.0.tar.gz --strip-components=1 -C /opt/wasi-sdk-24.0
          echo "WASI_SDK_PATH=/opt/wasi-sdk-24.0" >> "$GITHUB_ENV"
          rustup target add wasm32-wasip1
          rustup component add rustfmt clippy
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Build
        run: CC=${WASI_SDK_PATH}/bin/clang cargo build --target wasm32-wasip1 --release --features hterm
      - name: Run C linter
        run: cd c_lib && ${WASI_SDK_PATH}/bin/clang-tidy *.[ch] --warnings-as-errors='*' -- -I third_party
      - name: Run C formater
        run: |
          cd c_lib
          ${WASI_SDK_PATH}/bin/clang-format --style='{BasedOnStyle: llvm, IndentWidth: 4}' *.[ch] --Werror --dry-run
      - name: Run rust linter
        run: CC=${WASI_SDK_PATH}/bin/clang cargo clippy --target wasm32-wasip1 -- -Dwarnings
      - name: Run rust linter with hterm feature
        run: CC=${WASI_SDK_PATH}/bin/clang cargo clippy --target wasm32-wasip1 --features hterm -- -Dwarnings
      - name: Run Rust formater
        run: cargo fmt --check
